
POST http://localhost:8000/login
Content-Type: application/json

{
	"email": "leonardosclopes@gmail.com",
	"password": "1234"
}

###

GET http://localhost:8000/dashboard

###

GET http://localhost:8000/dashboard/companyProfile/5

###

POST http://localhost:8000/createCompany
Content-Type: application/json

{
	"name": "amazon",
	"address": "palo alto california",
	"area": "tecnologia",
	"site": "google.com",
	"tel": "123-456"
}

###

POST http://localhost:8000/dashboard/companyProfile/1234/createColaborator
Content-Type: application/json

{
	"name": "Leonardo Cristian",
	"surname": "Amorim Lopes",
	"email": "leonardosclopes@gmail.com",
	"tel": "123-456",
	"role": "T.I"
}

###

PUT http://localhost:8000/dashboard/editCompany/61b2946e8b56e6e546d7212d
Content-Type: application/json

{
	"newName": "aaaa nome",
	"newAddress": "novo address",
	"newArea": "nova area",
	"newSite": "novo site",
	"newTel": "novo telefone"
}

###

PUT http://localhost:8000/companyProfile/61b2946e8b56e6e546d7212d/editColaborator/61b29ee3196dfbd2f8631ce1
Content-Type: application/json

{
	"newName": "ssssss Cristian",
	"newSurname": "ssss Lopes",
	"newEmail": "sss@gmail.com",
	"newTel": "sss-456",
	"newRole": "sss.I"
}
###

DELETE  http://localhost:8000/dashboard/deleteCompany/61ae92ccd62255809b904580